version: '3.8'
services:
  backend:
    platform: linux/amd64
    build:
      context: backend
      dockerfile: backend.Dockerfile
    command: go run main.go
    tty: true
    volumes:
      - ./backend:/go/src
    ports:
      - "8000:8000"
  frontend:
    platform: linux/amd64
    build:
      context: frontend
      dockerfile: frontend.Dockerfile
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/app:/frontend/app
    stdin_open: true

    command: sh -c "npm run dev"