version: '3.8'
services:
  backend:
    platform: linux/amd64
    build:
      context: backend
      dockerfile: backend.Dockerfile
    command: go run main.go
    tty: true
    volumes:
      - ./backend:/go/src
    ports:
      - "8080:8080"
    depends_on:
      - db
  frontend:
    platform: linux/amd64
    build:
      context: frontend
      dockerfile: frontend.Dockerfile
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/:/frontend/
    stdin_open: true
    command: sh -c "npm run dev"
  db:
    platform: linux/amd64
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  backend_flask:
    build:
      context: backend_flask
      dockerfile: backend_flask.Dockerfile
    command: python3 backend_flask/main.py
    volumes:
      - ./backend_flask:/backend_flask
    ports:
      - "8000:8000"
    depends_on:
      - db

